"use client";
import Link from "next/link";
import { useState } from "react";
import { Shell } from "@/components/shell";
import { browserSupabase } from "@/lib/supabase-browser";
export default function Cadastro(){
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
 async function signup(){setMessage("");setLoading(true);try{const{error}=await browserSupabase().auth.signUp({email,password,options:{emailRedirectTo:location.origin+"/auth/callback"}});setMessage(error?.message||"Confira seu e-mail para confirmar sua conta.")}catch{setMessage("Configure o Supabase para ativar o cadastro.")}finally{setLoading(false)}}
 return <Shell><main className="auth-page"><div className="shell auth-wrap"><section className="auth-intro"><p className="eyebrow">Comunidade URBTRAIN</p><h1>A rua<br/>é nossa.</h1><p>Crie sua conta e fique perto de cada treino, evento e novidade da comunidade.</p></section><section className="auth-card" aria-labelledby="signup-title"><p className="eyebrow">Seu primeiro passo</p><h2 id="signup-title">Criar conta</h2><p>É rápido, simples e te conecta ainda mais à URBTRAIN.</p><div className="form"><label>E-mail<input className="form-control" type="email" autoComplete="email" placeholder="seuemail@exemplo.com" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Senha<input className="form-control" type="password" autoComplete="new-password" placeholder="Mínimo de 6 caracteres" value={password} onChange={event=>setPassword(event.target.value)}/></label><button className="button" type="button" onClick={signup} disabled={loading||!email||password.length<6}>{loading?"Criando conta...":"Criar minha conta"}</button><p className={"form-message "+(message&&!message.includes("Confira")?"error":"")} aria-live="polite">{message}</p></div><p className="auth-footer">Já tem uma conta? <Link href="/login">Entrar agora</Link></p></section></div></main></Shell>
}