"use client";
import Link from "next/link";
import { useState } from "react";
import { Shell } from "@/components/shell";
import { browserSupabase, configured } from "@/lib/supabase-browser";
export default function Login() {
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [showPassword,setShowPassword]=useState(false); const [loading,setLoading]=useState(false);
 async function login(){setMessage("");setLoading(true);try{const{error}=await browserSupabase().auth.signInWithPassword({email,password});setMessage(error?.message||"Login realizado. Bem-vindo de volta!")}catch{setMessage("Configure o Supabase para ativar o login.")}finally{setLoading(false)}}
 async function google(){setMessage("");try{await browserSupabase().auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+"/auth/callback"}})}catch{setMessage("Configure o Supabase para ativar o Google.")}}
 return <Shell><main className="auth-page"><div className="shell auth-wrap"><section className="auth-intro"><p className="eyebrow">Comunidade URBTRAIN</p><h1>Seu ritmo.<br/>Sua rua.</h1><p>Entre para acompanhar a comunidade, os próximos treinos e tudo o que movimenta a URBTRAIN.</p></section><section className="auth-card" aria-labelledby="login-title"><p className="eyebrow">Acesso à comunidade</p><h2 id="login-title">Bem-vindo de volta</h2><p>Use seus dados para continuar sua jornada com a gente.</p><div className="form"><label>E-mail<input className="form-control" type="email" autoComplete="email" placeholder="seuemail@exemplo.com" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Senha<div style={{position:"relative"}}><input className="form-control" style={{paddingRight:88}} type={showPassword?"text":"password"} autoComplete="current-password" placeholder="Sua senha" value={password} onChange={event=>setPassword(event.target.value)}/><button type="button" onClick={()=>setShowPassword(!showPassword)} style={{position:"absolute",right:8,top:8,border:0,background:"transparent",color:"#555",fontSize:".72rem",fontWeight:700,cursor:"pointer",textTransform:"uppercase"}}>{showPassword?"Ocultar":"Mostrar"}</button></div></label><button className="button" type="button" onClick={login} disabled={loading||!email||!password}>{loading?"Entrando...":"Entrar"}</button><div className="form-divider">ou</div><button className="button social" type="button" onClick={google} disabled={!configured}>Continuar com Google</button><p className={"form-message "+(message&&!message.includes("realizado")?"error":"")} aria-live="polite">{message}</p></div><p className="auth-footer">Ainda não faz parte? <Link href="/cadastro">Criar minha conta</Link></p></section></div></main></Shell>
}